"""initial schema

Revision ID: 149cfeb5cf25
Revises: 
Create Date: 2026-02-16 10:39:14.671141+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '149cfeb5cf25'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=True),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('bio', sa.String(length=2000), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('characters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('short_description', sa.String(length=500), nullable=True),
    sa.Column('species', sa.String(length=64), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('pronouns', sa.String(length=32), nullable=False),
    sa.Column('sprite_key', sa.String(length=64), nullable=False),
    sa.Column('portrait_url', sa.String(length=512), nullable=True),
    sa.Column('personality', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('appearance', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('background', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sim_state', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('skills', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('is_active_in_sim', sa.Boolean(), nullable=False),
    sa.Column('import_source', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_characters_owner_id'), 'characters', ['owner_id'], unique=False)
    op.create_table('worlds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_worlds_owner_id'), 'worlds', ['owner_id'], unique=False)
    op.create_table('locations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('world_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('location_type', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('position_x', sa.Float(), nullable=False),
    sa.Column('position_y', sa.Float(), nullable=False),
    sa.Column('available_activities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tile_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locations_world_id'), 'locations', ['world_id'], unique=False)
    op.create_table('memories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('character_id', sa.UUID(), nullable=False),
    sa.Column('memory_type', sa.String(length=64), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('emotional_valence', sa.Float(), nullable=False),
    sa.Column('importance', sa.Float(), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sim_timestamp', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memories_character_id'), 'memories', ['character_id'], unique=False)
    op.create_table('relationships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_character_id', sa.UUID(), nullable=False),
    sa.Column('target_character_id', sa.UUID(), nullable=False),
    sa.Column('friendship_score', sa.Float(), nullable=False),
    sa.Column('romance_score', sa.Float(), nullable=False),
    sa.Column('rivalry_score', sa.Float(), nullable=False),
    sa.Column('relationship_type', sa.String(length=64), nullable=False),
    sa.Column('interaction_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_character_id', 'target_character_id', name='uq_relationship_source_target')
    )
    op.create_index(op.f('ix_relationships_source_character_id'), 'relationships', ['source_character_id'], unique=False)
    op.create_index(op.f('ix_relationships_target_character_id'), 'relationships', ['target_character_id'], unique=False)
    op.create_table('simulation_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('world_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('involved_character_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sim_tick', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulation_events_sim_tick'), 'simulation_events', ['sim_tick'], unique=False)
    op.create_index(op.f('ix_simulation_events_world_id'), 'simulation_events', ['world_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_simulation_events_world_id'), table_name='simulation_events')
    op.drop_index(op.f('ix_simulation_events_sim_tick'), table_name='simulation_events')
    op.drop_table('simulation_events')
    op.drop_index(op.f('ix_relationships_target_character_id'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_source_character_id'), table_name='relationships')
    op.drop_table('relationships')
    op.drop_index(op.f('ix_memories_character_id'), table_name='memories')
    op.drop_table('memories')
    op.drop_index(op.f('ix_locations_world_id'), table_name='locations')
    op.drop_table('locations')
    op.drop_index(op.f('ix_worlds_owner_id'), table_name='worlds')
    op.drop_table('worlds')
    op.drop_index(op.f('ix_characters_owner_id'), table_name='characters')
    op.drop_table('characters')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
